server:
  port: 9990
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/facebook
    username: root
    password: Xworkzodc@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true